name: jake-training-env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pytorch=2.1.0
  - pip:
    - transformers==4.34.0
    - bitsandbytes==0.41.1
    - accelerate==0.23.0
    - peft==0.5.0
    - datasets
    - wandb
    - azureml-core
    - azureml-defaults
    - azureml-mlflow
    - azureml-telemetry
    - azure-storage-blob
    - PyYAML
